# Generated by Django 2.0.10 on 2019-02-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_settings_search_terms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchTerm',
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
    ]
