# Generated by Django 2.0.10 on 2019-02-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20190220_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchresult',
            old_name='where',
            new_name='location',
        ),
    ]
